---
platform: linux

image_resource:
  type: docker-image
  source: {repository: peppequa/dummy}

inputs:
- name: ci-concourse
- name: ansible

run:
  path: ./ci-concourse/ci-rehoming/scripts/run_ansible_destroy_green.sh