---
platform: linux

image_resource:
  type: docker-image
  source: {repository: peppequa/dummy}

inputs:
- name: ci-concourse
- name: playbooks
  path: playbooks

run:
  path: ./ci-concourse/ci-rehoming/scripts/run_ansible.sh