---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
- name: ci-concourse
- name: ansible

outputs:
- name: context

run:
  path: ./ci-concourse/ci-rehoming/scripts/prepare_docker.sh